name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install runtimes with asdf
        uses: asdf-vm/actions/install@v3
        with:
          asdf_global_file: .tool-versions
          cache: true

      - run: npm ci
      - run: npm test
